# Generated by Django 3.0.1 on 2019-12-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
