# Generated by Django 3.0.1 on 2019-12-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20191227_1908'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SendMail',
        ),
        migrations.AddField(
            model_name='job',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
