# Generated by Django 3.0.1 on 2019-12-27 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_devtools_framework_intro_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intro',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='intro',
            name='devtools',
        ),
        migrations.RemoveField(
            model_name='intro',
            name='framework',
        ),
        migrations.RemoveField(
            model_name='intro',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='intro',
            name='skills_image',
        ),
        migrations.DeleteModel(
            name='devtools',
        ),
        migrations.DeleteModel(
            name='framework',
        ),
        migrations.DeleteModel(
            name='languages',
        ),
    ]
